[package]
name = "detect-indent"
description = "Detect the indentation of code"
version = "0.1.0"
authors = ["Stefan Penner <stefan.penner@gmail.com>"]

[dependencies]
regex = "0.2"
lazy_static = "1.0.0"
